"""
Create model User, Create model Permission, Create model ExternalIdentity, Create model UserPermission, Create model Post, Create model Comment

Generated by Zeeb ORM on 2026-08-06 11:25
"""

import sqlalchemy as sa
from zeeb_orm.migrations import Migration, operations


class Migration(Migration):

    initial = True

    dependencies = []

    operations = [
    operations.CreateModel(
        name='User',
        table='accounts_user',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('password', sa.String(128)),
            sa.Column('last_login', sa.DateTime()),
            sa.Column('email', sa.String(254), nullable=False),
            sa.Column('username', sa.String(150)),
            sa.Column('first_name', sa.String(150)),
            sa.Column('last_name', sa.String(150)),
            sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
            sa.Column('is_staff', sa.Boolean(), nullable=False, default=False),
            sa.Column('is_superuser', sa.Boolean(), nullable=False, default=False),
            sa.Column('date_joined', sa.DateTime()),
        ],
        primary_key=['id'],
        constraints=[
            sa.UniqueConstraint('username', name='uq_accounts_user_username'),
            sa.UniqueConstraint('email', name='uq_accounts_user_email'),
        ],
    ),
    operations.CreateModel(
        name='Permission',
        table='auth_permissions',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('name', sa.String(255), nullable=False),
            sa.Column('codename', sa.String(100), nullable=False),
        ],
        primary_key=['id'],
        constraints=[
            sa.UniqueConstraint('codename', name='uq_auth_permissions_codename'),
        ],
    ),
    operations.CreateModel(
        name='ExternalIdentity',
        table='auth_external_identities',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), sa.ForeignKey('accounts_user.id', ondelete='CASCADE'), nullable=False),
            sa.Column('provider', sa.String(64), nullable=False),
            sa.Column('subject', sa.String(255), nullable=False),
            sa.Column('email', sa.String(254)),
            sa.Column('extra_data', sa.JSON()),
            sa.Column('created_at', sa.DateTime()),
            sa.Column('last_login_at', sa.DateTime()),
        ],
        primary_key=['id'],
        constraints=[
            sa.UniqueConstraint('provider', 'subject', name='uq_auth_external_identities_provider_subject'),
        ],
    ),
    operations.CreateModel(
        name='UserPermission',
        table='auth_user_permissions',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), sa.ForeignKey('accounts_user.id', ondelete='CASCADE'), nullable=False),
            sa.Column('permission_id', sa.Uuid(), sa.ForeignKey('auth_permissions.id', ondelete='CASCADE'), nullable=False),
        ],
        primary_key=['id'],
    ),
    operations.CreateModel(
        name='Post',
        table='post_post',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('title', sa.String(200), nullable=False),
            sa.Column('slug', sa.String(220), nullable=False),
            sa.Column('body', sa.Text(), nullable=False),
            sa.Column('published', sa.Boolean(), nullable=False, default=False),
            sa.Column('author_id', sa.Uuid(), sa.ForeignKey('accounts_user.id', ondelete='CASCADE'), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
        ],
        primary_key=['id'],
        constraints=[
            sa.UniqueConstraint('slug', name='uq_post_post_slug'),
        ],
    ),
    operations.CreateModel(
        name='Comment',
        table='comment_comment',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('post_id', sa.Uuid(), sa.ForeignKey('post_post.id', ondelete='CASCADE'), nullable=False),
            sa.Column('author_id', sa.Uuid(), sa.ForeignKey('accounts_user.id', ondelete='CASCADE'), nullable=False),
            sa.Column('body', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
        ],
        primary_key=['id'],
    ),
    ]
