"""
Create model Permission, Create model User, Create model UserPermission

Generated by Zeeb ORM on 2026-03-05 14:23
"""

import sqlalchemy as sa
from zeeb_orm.migrations import Migration, operations


class Migration(Migration):

    initial = True

    dependencies = []

    operations = [
    operations.CreateModel(
        name='Permission',
        table='auth_permissions',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('name', sa.String(255), nullable=False),
            sa.Column('codename', sa.String(100), nullable=False),
        ],
        primary_key=['id'],
    ),
    operations.CreateModel(
        name='User',
        table='auth_users',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('password', sa.String(128)),
            sa.Column('last_login', sa.DateTime()),
            sa.Column('email', sa.String(254), nullable=False),
            sa.Column('username', sa.String(150)),
            sa.Column('first_name', sa.String(150)),
            sa.Column('last_name', sa.String(150)),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('is_staff', sa.Boolean(), nullable=False),
            sa.Column('is_superuser', sa.Boolean(), nullable=False),
            sa.Column('date_joined', sa.DateTime()),
        ],
        primary_key=['id'],
    ),
    operations.CreateModel(
        name='UserPermission',
        table='auth_user_permissions',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('permission_id', sa.Uuid(), nullable=False),
        ],
        primary_key=['id'],
    ),
    ]
