"""
Create model Comment

Generated by Zeeb ORM on 2026-03-05 14:23
"""

import sqlalchemy as sa
from zeeb_orm.migrations import Migration, operations


class Migration(Migration):

    dependencies = ['0002_post_post']

    operations = [
    operations.CreateModel(
        name='Comment',
        table='comment_comment',
        columns=[
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('name', sa.String(100), nullable=False),
            sa.Column('description', sa.Text()),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
        ],
        primary_key=['id'],
    ),
    ]
