"""Guards on the scaffolding templates themselves.

The templates are rendered with ``str.format``, so an unescaped brace or a
typo'd setting name only surfaces when someone actually scaffolds a project.
These checks catch both at test time.
"""

import ast
import re

import pytest

from zeeb_agents import test_scaffold
from zeeb_orm.scaffold import accounts, harness, wiring
from zeeb_orm.scaffold import app as app_templates
from zeeb_orm.scaffold import project as project_templates

PROJECT_MODULES = {
    "MANAGE_PY": {},
    "SETTINGS_PY": {"project_name": "demo_api"},
    "URLS_PY": {},
    "ASGI_PY": {"project_name": "demo_api"},
    "PROJECT_INIT_PY": {"project_name": "demo_api"},
    "APPS_INIT_PY": {},
}

APP_CONTEXT = {
    "app_name": "shop",
    "app_class": "Shop",
    "app_title": "Shop",
    "model_name": "Shop",
    "model_slug": "shop",
    "table_name": "shop_shop",
    "route_prefix": "shops",
}


def render(template: str, context: dict) -> str:
    return template.format(**context) if context else template


@pytest.mark.parametrize("name,context", PROJECT_MODULES.items())
def test_project_templates_compile(name, context):
    source = render(getattr(project_templates, name), context)
    compile(source, f"{name}.py", "exec")


@pytest.mark.parametrize(
    "name",
    [
        "MODELS_PY",
        "SERIALIZERS_PY",
        "VIEWS_PY",
        "URLS_PY",
        "APP_INIT_PY",
        "TESTS_PY",
        "SLICE_MODELS_PY",
        "SLICE_SERIALIZERS_PY",
        "SLICE_VIEWS_PY",
        "SLICE_URLS_PY",
        "SLICE_TESTS_PY",
    ],
)
def test_app_templates_compile(name):
    compile(getattr(app_templates, name).format(**APP_CONTEXT), f"{name}.py", "exec")


@pytest.mark.parametrize(
    "name", ["MODELS_PY", "SERIALIZERS_PY", "VIEWS_PY", "URLS_PY", "TESTS_PY"]
)
def test_the_default_app_templates_teach_through_their_docstring(name):
    """The canonical example lives in the docstring, not in commented-out code.

    A comment neither lints nor runs, and an agent that copies one gets a
    comment. The docstring survives every edit to the file below it.
    """
    module = ast.parse(getattr(app_templates, name).format(**APP_CONTEXT))
    docstring = ast.get_docstring(module)
    assert docstring, f"{name} has no module docstring"
    if name != "TESTS_PY":
        assert APP_CONTEXT["model_name"] in docstring, f"{name} shows no example"


@pytest.mark.parametrize("name", ["MODELS_PY", "SERIALIZERS_PY", "VIEWS_PY", "URLS_PY"])
def test_accounts_templates_compile(name):
    compile(getattr(accounts, name), f"accounts_{name}.py", "exec")


def test_the_test_harness_lives_in_one_place():
    """A feature generated by the agent layer runs against the CLI's fixtures."""
    assert test_scaffold._CONFTEST is harness.CONFTEST_PY
    assert test_scaffold._PYTEST_INI is harness.PYTEST_INI


@pytest.mark.parametrize("source", ["conftest", "smoke"])
def test_the_harness_templates_compile(source):
    rendered = (
        harness.render_conftest("demo_api.settings")
        if source == "conftest"
        else harness.SMOKE_TEST_PY
    )
    compile(rendered, f"{source}.py", "exec")


def test_no_placeholder_survives_rendering():
    """An unresolved @NAME@ would reach the project as a syntax error."""
    assert not re.search(r"@[A-Z_]+@", harness.render_conftest("demo_api.settings"))


def test_the_project_urls_template_has_one_definition():
    """The repair template and the scaffolded file must not drift apart."""
    assert project_templates.URLS_PY is wiring.STANDARD_URLS_TEMPLATE


def test_the_urls_template_imports_no_app():
    """It is written into arbitrary projects, so it cannot assume an app."""
    assert "apps." not in wiring.STANDARD_URLS_TEMPLATE


def test_the_urls_template_stays_wireable():
    """`append_router_include` refuses a urls.py it cannot edit safely."""
    tree = ast.parse(wiring.STANDARD_URLS_TEMPLATE)
    assigned = {
        target.id
        for node in tree.body
        if isinstance(node, ast.Assign)
        for target in node.targets
        if isinstance(target, ast.Name)
    }
    assert "router" in assigned
    assert any(
        isinstance(node, ast.FunctionDef) and node.name == "get_routes" for node in tree.body
    )


def test_the_auth_include_appears_exactly_once():
    """setup_auth counts this exact prefix to detect a duplicate include."""
    assert wiring.STANDARD_URLS_TEMPLATE.count("router.include(create_auth_router(") == 1


def test_generated_secret_keys_are_strong_and_unique():
    from zeeb_api.auth.jwt import INSECURE_SECRETS

    keys = {project_templates.generate_secret_key() for _ in range(20)}
    assert len(keys) == 20
    for key in keys:
        assert key not in INSECURE_SECRETS
        assert len(key) >= 43
        # No quoting needed in a .env file.
        assert not set(key) & set("#= \n\"'")


# ---------------------------------------------------------------------------
# Drift guard: the scaffold may only set settings the framework reads
# ---------------------------------------------------------------------------

# Names the template defines for its own use rather than as framework settings.
TEMPLATE_LOCALS = {
    "BASE_DIR",
    "DEFAULT_DATABASE_URL",
    "_ANON_THROTTLE",
    "_USER_THROTTLE",
    "_HEADER_VERSIONING",
    "AUTH_URL_PREFIX",
    "AUTH_ENABLE_REGISTRATION",
    "AUTH_LOGIN_THROTTLE_RATE",
}


def scaffolded_setting_names() -> set[str]:
    source = project_templates.SETTINGS_PY.format(project_name="demo_api")
    return {
        target.id
        for node in ast.parse(source).body
        if isinstance(node, ast.Assign)
        for target in node.targets
        if isinstance(target, ast.Name) and target.id.isupper()
    }


def test_every_scaffolded_setting_is_a_real_one():
    """A typo'd setting name is silently ignored at runtime — catch it here."""
    from zeeb_api.conf import default_settings

    known = {name for name in dir(default_settings) if name.isupper()}
    unknown = scaffolded_setting_names() - known - TEMPLATE_LOCALS
    assert not unknown, f"settings.py sets names the framework never reads: {sorted(unknown)}"


def test_the_scaffold_turns_the_batteries_on():
    """The point of the boilerplate: these are configured, not left to chance."""
    source = project_templates.SETTINGS_PY.format(project_name="demo_api")
    for expected in (
        'AUTH_USER_MODEL = "accounts.User"',
        'ROOT_URLCONF = "demo_api.urls"',
        "zeeb_api.middleware.CORSMiddleware",
        "zeeb_api.versioning.VersioningMiddleware",
        "zeeb_api.middleware.JWTAuthMiddleware",
        "DEFAULT_THROTTLE_CLASSES",
        "DEFAULT_VERSIONING_CLASS",
        "OAUTH_PROVIDERS = env_oauth_providers()",
        "INSTALL_HEALTH_ROUTES = True",
    ):
        assert expected in source, expected


def test_the_rendered_settings_defaults(tmp_path):
    """Execute the template the way a project would and check the defaults."""
    from zeeb_api.conf.env import clear_env_cache

    clear_env_cache()
    settings_file = tmp_path / "demo_api" / "settings.py"
    settings_file.parent.mkdir()
    settings_file.write_text(project_templates.SETTINGS_PY.format(project_name="demo_api"))

    namespace: dict = {"__file__": str(settings_file)}
    exec(compile(settings_file.read_text(), str(settings_file), "exec"), namespace)

    # A non-empty origin list matters: install_middleware skips CORSMiddleware
    # entirely when it is empty, and describe_project reports that as a warning.
    assert namespace["CORS_ALLOW_ORIGINS"]
    assert namespace["DEBUG"] is True
    assert namespace["AUTH_USER_MODEL"] == "accounts.User"
    assert namespace["INSTALLED_APPS"] == ["apps.accounts"]
    assert namespace["OAUTH_PROVIDERS"] == {}
    assert namespace["ALLOWED_VERSIONS"] == ["1.0"]
    assert namespace["DEFAULT_THROTTLE_RATES"] == {"anon": "120/min", "user": "1200/min"}
    # Paths are anchored at the project root, not the working directory.
    assert str(tmp_path) in namespace["DATABASE"]["url"]


def test_provider_names_stay_out_of_the_settings_template():
    """`setup_oauth` treats a provider literal here as "already configured"."""
    source = project_templates.SETTINGS_PY.format(project_name="demo_api")
    oauth_section = source[source.index("OAUTH_PROVIDERS"):]
    for provider in ('"google"', '"github"', '"azure"'):
        assert provider not in oauth_section, provider


def test_the_settings_template_stays_single_line_assignable():
    """`manage_settings` can only rewrite a setting that fits on one line."""
    source = project_templates.SETTINGS_PY.format(project_name="demo_api")
    # Collection-valued settings are exempt: manage_settings only writes
    # scalars, so it would never target them anyway.
    multiline_ok = {
        "DATABASE",
        "INSTALLED_APPS",
        "MIDDLEWARE",
        "LOGGING",
        "DEFAULT_THROTTLE_RATES",
        "DEFAULT_THROTTLE_CLASSES",
        "CORS_ALLOW_ORIGINS",
    }
    for node in ast.parse(source).body:
        if not isinstance(node, ast.Assign):
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or not target.id.isupper():
            continue
        if target.id in multiline_ok:
            continue
        assert node.lineno == node.end_lineno, f"{target.id} spans multiple lines"
