"""
Migration file writer — generates Django-style migration files.

Produces files like ``0001_initial.py`` with a ``Migration`` class
containing ``dependencies`` and ``operations``.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from zeeb_orm.migrations.operations import Operation


def _slugify(text: str) -> str:
    """Convert text to a migration-name-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = text.strip("_")
    return text or "auto"


def next_migration_number(migrations_dir: Path) -> int:
    """Determine the next sequential migration number."""
    from zeeb_orm.migrations.executor import list_migration_files

    existing = list_migration_files(migrations_dir)
    if not existing:
        return 1
    # Parse the highest number
    last_name = existing[-1][0]
    match = re.match(r"^(\d{4})_", last_name)
    if match:
        return int(match.group(1)) + 1
    return len(existing) + 1


def write_migration(
    migrations_dir: Path,
    operations: list[Operation],
    name: str | None = None,
    dependencies: list[str] | None = None,
    initial: bool = False,
) -> Path:
    """
    Generate a new migration file.

    Args:
        migrations_dir: Directory to write the file in.
        operations: List of Operation objects.
        name: Human-readable name (e.g. "add_views_to_posts").
              Auto-generated if None.
        dependencies: List of migration names this depends on.
        initial: Whether this is the initial migration.

    Returns:
        Path to the created migration file.
    """
    from zeeb_orm.migrations.executor import list_migration_files

    migrations_dir.mkdir(parents=True, exist_ok=True)

    number = next_migration_number(migrations_dir)

    if name is None:
        if initial or number == 1:
            slug = "initial"
        else:
            # Auto-generate from operations
            slug = _auto_name(operations)
    else:
        slug = _slugify(name)

    filename = f"{number:04d}_{slug}.py"
    filepath = migrations_dir / filename
    migration_name = f"{number:04d}_{slug}"

    # Determine dependencies
    if dependencies is None:
        existing = list_migration_files(migrations_dir)
        # Filter out the file we're about to create
        existing = [(n, p) for n, p in existing if n != migration_name]
        if existing:
            dependencies = [existing[-1][0]]
        else:
            dependencies = []

    content = _render_migration(
        migration_name=migration_name,
        operations=operations,
        dependencies=dependencies,
        initial=initial or number == 1,
    )

    filepath.write_text(content)
    return filepath


def _auto_name(operations: list[Operation]) -> str:
    """Generate a name from the operations list."""
    from zeeb_orm.migrations import operations as ops_module

    descriptions = []
    for op in operations[:3]:
        if isinstance(op, ops_module.CreateModel):
            descriptions.append(op.table)
        elif isinstance(op, ops_module.DeleteModel):
            descriptions.append(f"delete_{op.table}")
        elif isinstance(op, ops_module.AddField):
            descriptions.append(f"{op.table}_{op.name}")
        elif isinstance(op, ops_module.RemoveField):
            descriptions.append(f"remove_{op.name}_from_{op.table}")
        elif isinstance(op, ops_module.AlterField):
            descriptions.append(f"alter_{op.name}_on_{op.table}")
        else:
            descriptions.append("auto")

    name = "_".join(descriptions) if descriptions else "auto"
    if len(operations) > 3:
        name += "_and_more"
    return _slugify(name)


def _render_migration(
    migration_name: str,
    operations: list[Operation],
    dependencies: list[str],
    initial: bool,
) -> str:
    """Render the migration file content."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Build description from operations
    descriptions = [op.describe() for op in operations]
    description = ", ".join(descriptions) if descriptions else "Empty migration"

    lines = [
        f'"""',
        f"{description}",
        f"",
        f"Generated by Zeeb ORM on {timestamp}",
        f'"""',
        f"",
        f"import sqlalchemy as sa",
        f"from zeeb_orm.migrations import Migration, operations",
        f"",
        f"",
        f"class Migration(Migration):",
        f"",
    ]

    if initial:
        lines.append(f"    initial = True")
        lines.append(f"")

    # Dependencies
    lines.append(f"    dependencies = {dependencies!r}")
    lines.append(f"")

    # Operations
    lines.append(f"    operations = [")
    for op in operations:
        lines.append(f"{repr(op)},")
    lines.append(f"    ]")
    lines.append(f"")

    return "\n".join(lines)
