"""The test harness every scaffolded project ships with.

``pytest.ini``, ``tests/conftest.py`` and a smoke suite that passes on a project
that has never run a migration — the ``db`` fixture builds the schema from the
model registry rather than replaying migration files, so ``pytest`` is a working
verification loop from the first minute.

This lives in ``zeeb_orm`` for the same reason :mod:`zeeb_orm.scaffold.wiring`
does: ``zeeb startproject`` and ``zeeb_agents.generate_tests`` must write the
*same* fixtures, or a feature generated by the agent layer would run against a
conftest the CLI never heard of. The agent layer imports these constants.

Unlike the ``.py`` templates in :mod:`zeeb_orm.scaffold.app`, these are **not**
rendered with ``str.format``: the conftest is full of f-strings and dict
literals, and doubling every brace in a 150-line file is a standing merge
hazard. They use an ``@PLACEHOLDER@`` token and :func:`str.replace` instead.
"""

from __future__ import annotations

from pathlib import Path

SETTINGS_MODULE_PLACEHOLDER = "@SETTINGS_MODULE@"

PYTEST_INI = """\
[pytest]
asyncio_mode = auto
testpaths = tests
"""

CONFTEST_PY = '''\
"""Shared test fixtures for this project.

Written by `zeeb startproject`; `build_feature` adds files to this directory
and never overwrites. Safe to edit — nothing regenerates it.

Fixtures:
    app           the project's FastAPI application
    api_prefix    settings.API_PREFIX (default "/api/v1")
    db            schema created, every table emptied before each test
    client        anonymous httpx client against the app
    user          an ordinary saved user
    auth_client   client carrying that user's bearer token
    admin_user    a staff/superuser account
    admin_client  client carrying the admin's bearer token
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Isolated test database — fresh file per test run, env wins over settings.
_TEST_DB = PROJECT_ROOT / "test_db.sqlite3"
_TEST_DB.unlink(missing_ok=True)
os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{_TEST_DB}"

# Token minting needs a secret that passes the strength check. Only set when the
# environment has none, so a project with real auth config keeps using it.
os.environ.setdefault("JWT_SECRET_KEY", "generated-tests-only-secret-" + "z" * 32)

# Tests hammer the same endpoints from one client, which the default rate limits
# are there to stop. Lift them for the run only; setdefault keeps a value the
# developer set deliberately.
os.environ.setdefault("THROTTLE_ANON_RATE", "1000000/min")
os.environ.setdefault("THROTTLE_USER_RATE", "1000000/min")
os.environ.setdefault("AUTH_LOGIN_THROTTLE_RATE", "1000000/min")

SETTINGS_MODULE = "@SETTINGS_MODULE@"


@pytest.fixture(scope="session")
def app():
    from zeeb_api import create_app

    return create_app(SETTINGS_MODULE)


@pytest.fixture(scope="session")
def api_prefix(app):
    from zeeb_api.conf import get_settings

    return getattr(get_settings(), "API_PREFIX", "") or ""


def _import_all_models():
    """Import every installed app's models module.

    A model only enters the registry when its module is imported, and the schema
    is built from the registry. Without this, a project with a custom user model
    fails at create_all: the framework's own auth tables carry a foreign key to
    a user table that nothing has defined yet.
    """
    import importlib

    from zeeb_api.conf import get_settings

    for app_path in getattr(get_settings(), "INSTALLED_APPS", None) or []:
        try:
            importlib.import_module(f"{app_path}.models")
        except ModuleNotFoundError:
            pass  # app without models is fine


@pytest.fixture()
async def db(app):
    """Connected database with all model tables created, emptied before each test.

    The schema comes from the model registry, not from replaying migrations —
    that is what lets `pytest` pass on a freshly created project before
    `makemigrations` has ever run.

    The sqlite file lives for the whole run, so without the wipe one test's rows
    (a uniqueness fixture, say) collide with another's sample values and the
    suite passes or fails depending on ordering.
    """
    from sqlalchemy import delete
    from zeeb_orm.db.connection import get_database, setup_database
    from zeeb_orm.models.base import _model_registry, metadata

    _import_all_models()
    # Tables build lazily — materialize every registered model before create_all.
    for model in list(_model_registry.values()):
        model._get_table()
    database = get_database()
    if database is None:
        database = await setup_database(os.environ["DATABASE_URL"])
    await database.create_all()
    # Children before parents so foreign keys never block the wipe.
    # Database.execute commits each statement itself.
    for table in reversed(metadata.sorted_tables):
        await database.execute(delete(table))
    return database


@pytest.fixture()
async def client(app, db):
    from httpx import ASGITransport, AsyncClient

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as c:
        yield c


async def _make_user(label, **extra):
    """Create a saved user, or skip the test when the project has no user model.

    The email is unique per call: the test database persists across tests in a
    run, so a fixed address collides on the unique constraint from the second
    test onwards.
    """
    import uuid

    try:
        from zeeb_api.auth.backends import get_user_model

        User = get_user_model()  # noqa: N806  (a class, despite the assignment)
    except Exception as exc:  # no AUTH_USER_MODEL wired yet
        pytest.skip(f"project has no user model configured ({exc})")
    user = User(email=f"tests-{label}-{uuid.uuid4().hex[:12]}@example.com", **extra)
    if hasattr(user, "set_password"):
        user.set_password("tests-only-password")
    await user.save()
    return user


async def _bearer_client(app, user):
    from httpx import ASGITransport, AsyncClient
    from zeeb_api.auth.jwt import create_access_token

    headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
    return AsyncClient(transport=ASGITransport(app=app), base_url="http://test", headers=headers)


@pytest.fixture()
async def user(db):
    """An ordinary active user."""
    return await _make_user("user")


@pytest.fixture()
async def auth_client(app, db, user):
    """Client authenticated as an ordinary user."""
    async with await _bearer_client(app, user) as c:
        yield c


@pytest.fixture()
async def admin_user(db):
    """A staff/superuser account, for endpoints gated on IsAdminUser."""
    from zeeb_api.auth.backends import get_user_model

    User = get_user_model()  # noqa: N806  (a class, despite the assignment)
    extra = {flag: True for flag in ("is_staff", "is_superuser") if hasattr(User, flag)}
    return await _make_user("admin", **extra)


@pytest.fixture()
async def admin_client(app, db, admin_user):
    """Client authenticated as a staff user."""
    async with await _bearer_client(app, admin_user) as c:
        yield c
'''

SMOKE_TEST_PY = '''\
"""Smoke tests for the project itself — what `startproject` already wired up.

These pass on a fresh project before any migration has run: the `db` fixture
builds the schema from the model registry. Run them with:

    pytest -q

Keep them. They are the fastest signal that settings, the database, the auth
router, the JWT middleware and the permission layer are all still intact.
"""

async def test_the_health_probes_answer(client):
    """Both probes live at the root, not under the API prefix."""
    health = await client.get("/health")
    assert health.status_code == 200, health.text
    assert health.json() == {"status": "ok"}

    ready = await client.get("/ready")
    assert ready.status_code == 200, ready.text
    assert ready.json()["status"] == "ready"


async def test_the_openapi_schema_is_served(client):
    """A broken route or serializer shows up here before it shows up in a browser."""
    response = await client.get("/openapi.json")
    assert response.status_code == 200, response.text
    assert response.json()["paths"]


async def test_the_project_owns_its_user_model(db):
    """AUTH_USER_MODEL points at apps/accounts/models.py, not at the framework's."""
    from zeeb_api.auth.backends import get_user_model

    from apps.accounts.models import User

    assert get_user_model() is User
    assert User._meta.db_table == "accounts_user"


async def test_register_login_and_me(client, api_prefix):
    """One round trip proves settings, JWT config, the database, the auth router
    and JWTAuthMiddleware are all wired."""
    credentials = {"email": "smoke@example.com", "password": "smoke-test-password"}

    registered = await client.post(f"{api_prefix}/auth/register", json=credentials)
    assert registered.status_code == 200, registered.text

    logged_in = await client.post(f"{api_prefix}/auth/login", json=credentials)
    assert logged_in.status_code == 200, logged_in.text
    tokens = logged_in.json()
    assert tokens["token_type"] == "bearer"
    assert tokens["access_token"] and tokens["refresh_token"]

    me = await client.get(
        f"{api_prefix}/auth/me",
        headers={"Authorization": f"Bearer {tokens['access_token']}"},
    )
    assert me.status_code == 200, me.text
    assert me.json()["claims"]["email"] == credentials["email"]


async def test_the_user_directory_is_staff_only(client, auth_client, api_prefix):
    """The canary that permission classes are actually enforced.

    Delete this if you deliberately open the user directory.
    """
    assert (await client.get(f"{api_prefix}/users")).status_code == 401
    assert (await auth_client.get(f"{api_prefix}/users")).status_code == 403
'''


def find_settings_module(project_root: Path) -> str | None:
    """Return ``"<package>.settings"`` for a project on disk, or ``None``.

    The settings package is the first top-level directory that holds a
    ``settings.py``; ``apps`` is skipped because a scaffolded app never has one.
    """
    for item in sorted(Path(project_root).iterdir()):
        if item.is_dir() and item.name != "apps" and (item / "settings.py").exists():
            return f"{item.name}.settings"
    return None


def render_conftest(settings_module: str) -> str:
    """``CONFTEST_PY`` with its settings-module placeholder resolved."""
    return CONFTEST_PY.replace(SETTINGS_MODULE_PLACEHOLDER, settings_module)


def ensure_test_scaffold(project_root: Path) -> list[str]:
    """Write the shared harness files that are missing, never overwriting.

    Repair semantics on purpose: a project scaffolded before this existed picks
    the files up on its next ``startapp``, and a conftest the developer has
    edited is left alone. Returns the project-relative paths written.

    Returns an empty list when the project has no settings package — there is
    nothing to point the conftest at, and guessing would produce a file that
    fails at import.
    """
    root = Path(project_root)
    settings_module = find_settings_module(root)
    if settings_module is None:
        return []

    written: list[str] = []
    for relative, content in (
        ("pytest.ini", PYTEST_INI),
        ("tests/__init__.py", ""),
        ("tests/conftest.py", render_conftest(settings_module)),
    ):
        path = root / relative
        if path.exists():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(relative)
    return written
