"""Project file templates for ``zeeb startproject``.

Rendered with ``str.format(project_name=...)``, so every literal brace in a
template is doubled. ``ENV_TEMPLATE`` additionally takes ``secret_key=``.
"""

import secrets

from zeeb_orm.scaffold.wiring import STANDARD_URLS_TEMPLATE


def generate_secret_key() -> str:
    """Return a fresh per-project signing key for the generated ``.env``.

    ``token_urlsafe`` yields only ``[A-Za-z0-9_-]``, so the value needs no
    quoting in a ``.env`` file and can never contain ``#``, ``=`` or a newline.
    64 bytes is well above the 32 that HS256 wants, and the result is by
    construction not one of ``zeeb_api.auth.jwt.INSECURE_SECRETS`` — which is
    what lets a generated project run with ``DEBUG=false`` out of the box.
    """
    return secrets.token_urlsafe(64)


PYPROJECT_TOML = '''\
# Project identity and tool configuration.
#
# [tool.zeeb] is how tooling recognises this directory as a Zeeb project
# without importing anything. Every other fact about the project — its apps,
# models and routes — is read live with `python manage.py inspect --json`,
# because a checked-in inventory is stale the moment a file is edited.
#
# There is deliberately no [project] table: dependencies live in
# requirements.txt, and declaring them twice guarantees they drift.

[tool.zeeb]
framework = "zeebpy"
project = "{project_name}"
package = "{project_name}"
settings_module = "{project_name}.settings"
created_with = "{zeeb_version}"

[tool.ruff]
line-length = 100
target-version = "py310"
# Migrations are generated by `makemigrations` and must not be hand-edited, so
# linting them would only ever produce findings nobody may act on.
exclude = ["migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]
'''


def zeeb_version() -> str:
    """Installed zeebpy version, or ``"unknown"`` from a source checkout."""
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("zeebpy")
    except PackageNotFoundError:
        return "unknown"


MANAGE_PY = '''#!/usr/bin/env python3
"""Zeeb project management script."""

import sys
from pathlib import Path

# Add project to path
sys.path.insert(0, str(Path(__file__).parent))

if __name__ == "__main__":
    from zeeb_orm.cli.main import main
    sys.exit(main())
'''

SETTINGS_PY = '''"""
{project_name} settings.

Every setting below is environment-driven: the literal is the default used when
the variable is absent. Change behavior by editing ``.env`` (gitignored) or by
setting real environment variables — real environment variables always win.
``.env.example`` documents every supported variable.

Value grammar: booleans accept 1/true/yes/on and 0/false/no/off; lists are
comma-separated; an empty value means "explicitly empty", not "use the default".
"""

from pathlib import Path

from zeeb_api.conf.env import (
    env_bool,
    env_int,
    env_list,
    env_oauth_providers,
    env_str,
    load_env,
)

# The directory holding manage.py. Every path below is anchored here, so the
# settings behave identically no matter which directory the process runs from —
# the CLI, the agent tooling and the test suite all load this file by path,
# never by working directory.
BASE_DIR = Path(__file__).resolve().parent.parent

load_env(BASE_DIR / ".env")

# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------

DEBUG = env_bool("DEBUG", True)

# The real signing key lives in .env, generated per project and never committed.
# This fallback is a known-insecure sentinel on purpose: with DEBUG off and no
# SECRET_KEY in the environment, create_app() refuses to start rather than
# silently signing tokens with a guessable key.
SECRET_KEY = env_str("SECRET_KEY", "INSECURE-DEFAULT-KEY-CHANGE-IN-PRODUCTION")

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------
# PostgreSQL: DATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/db
# MySQL:      DATABASE_URL=mysql+aiomysql://user:password@localhost:3306/db

DEFAULT_DATABASE_URL = f"sqlite+aiosqlite:///{{BASE_DIR / 'db.sqlite3'}}"
DATABASE = {{"url": env_str("DATABASE_URL", DEFAULT_DATABASE_URL)}}

# Refuse to start with unapplied migrations (a warning instead under DEBUG).
ENFORCE_MIGRATIONS = env_bool("ENFORCE_MIGRATIONS", True)

# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------
# 'zeeb startapp <name>' appends to this list for you.

INSTALLED_APPS = [
    "apps.accounts",
]

# This project's own user model, in apps/accounts/models.py. Everything that
# resolves a user goes through it: the auth endpoints, createsuperuser, and
# every ForeignKey pointing at "accounts.User".
AUTH_USER_MODEL = "accounts.User"
AUTH_LOAD_USER_FROM_DB = env_bool("AUTH_LOAD_USER_FROM_DB", True)

# ---------------------------------------------------------------------------
# API surface
# ---------------------------------------------------------------------------

ROOT_URLCONF = "{project_name}.urls"
API_TITLE = env_str("API_TITLE", "{project_name} API")
API_DESCRIPTION = env_str("API_DESCRIPTION", "")
API_VERSION = env_str("API_VERSION", "1.0.0")
API_PREFIX = env_str("API_PREFIX", "/api/v1")

# /health (liveness) and /ready (readiness, checks the database) are registered
# by create_app(); the standard error envelope is installed the same way.
INSTALL_HEALTH_ROUTES = True
INSTALL_EXCEPTION_HANDLERS = True

DEFAULT_LIMIT = env_int("DEFAULT_LIMIT", 20)
MAX_LIMIT = env_int("MAX_LIMIT", 100)

# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------
# The first entry is the outermost. CORS wraps everything so even a rejected
# request answers with CORS headers instead of an opaque browser error;
# versioning resolves the requested API version before any view runs;
# JWTAuthMiddleware resolves the Bearer token and sets request.state.user, which
# every ViewSet permission class reads. CORSMiddleware is skipped automatically
# while CORS_ALLOW_ORIGINS is empty.

MIDDLEWARE = [
    "zeeb_api.middleware.CORSMiddleware",
    "zeeb_api.versioning.VersioningMiddleware",
    "zeeb_api.middleware.JWTAuthMiddleware",
]

# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

CORS_ALLOW_ORIGINS = env_list("CORS_ALLOW_ORIGINS", ["http://localhost:3000", "http://localhost:5173"])
# For a frontend whose hostname changes per build — a Lovable, Vercel or
# Netlify preview — an exact origin list would need editing on every deploy.
# Anchor the pattern and escape the dots: an unanchored ".vercel.app" also
# matches "https://evil-vercel.app.attacker.com".
CORS_ALLOW_ORIGIN_REGEX = env_str("CORS_ALLOW_ORIGIN_REGEX", "") or None
CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", True)
CORS_ALLOW_METHODS = env_list("CORS_ALLOW_METHODS", ["*"])
CORS_ALLOW_HEADERS = env_list("CORS_ALLOW_HEADERS", ["*"])
CORS_EXPOSE_HEADERS = env_list("CORS_EXPOSE_HEADERS", [])
CORS_MAX_AGE = env_int("CORS_MAX_AGE", 600)

# ---------------------------------------------------------------------------
# Authentication (JWT)
# ---------------------------------------------------------------------------
# The endpoints are mounted in urls.py: POST <prefix>/login, /register,
# /refresh, /logout and GET <prefix>/me.

JWT_SECRET_KEY = env_str("JWT_SECRET_KEY", SECRET_KEY)
JWT_ALGORITHM = env_str("JWT_ALGORITHM", "HS256")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = env_int("JWT_ACCESS_TOKEN_EXPIRE_MINUTES", 60)
JWT_REFRESH_TOKEN_EXPIRE_DAYS = env_int("JWT_REFRESH_TOKEN_EXPIRE_DAYS", 7)
JWT_ISSUER = env_str("JWT_ISSUER", None)
JWT_AUDIENCE = env_str("JWT_AUDIENCE", None)

AUTH_URL_PREFIX = env_str("AUTH_URL_PREFIX", "/auth")
AUTH_ENABLE_REGISTRATION = env_bool("AUTH_ENABLE_REGISTRATION", True)
# Per-client limit on /login and /register — the credential-stuffing brake.
# Set it empty to turn it off.
AUTH_LOGIN_THROTTLE_RATE = env_str("AUTH_LOGIN_THROTTLE_RATE", "10/min")

# ---------------------------------------------------------------------------
# OAuth2 / OIDC   (pip install "zeebpy[oauth]")
# ---------------------------------------------------------------------------
# A provider activates the moment its client id is in the environment:
#   GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET
#   GITHUB_CLIENT_ID / GITHUB_CLIENT_SECRET
#   AZURE_CLIENT_ID  / AZURE_CLIENT_SECRET / AZURE_TENANT_ID (default "common")
# With none set this stays empty and urls.py mounts no OAuth route at all.

OAUTH_PROVIDERS = env_oauth_providers()
OAUTH_AUTO_CREATE_USERS = env_bool("OAUTH_AUTO_CREATE_USERS", True)
OAUTH_LINK_BY_EMAIL = env_bool("OAUTH_LINK_BY_EMAIL", True)
OAUTH_REQUIRE_VERIFIED_EMAIL = env_bool("OAUTH_REQUIRE_VERIFIED_EMAIL", True)
OAUTH_STATE_TTL_SECONDS = env_int("OAUTH_STATE_TTL_SECONDS", 600)
OAUTH_REDIRECT_URI = env_str("OAUTH_REDIRECT_URI", None)
OAUTH_SUCCESS_REDIRECT = env_str("OAUTH_SUCCESS_REDIRECT", None)
OAUTH_ALLOWED_REDIRECT_HOSTS = env_list("OAUTH_ALLOWED_REDIRECT_HOSTS", [])
OAUTH_ACCEPT_EXTERNAL_TOKENS = env_list("OAUTH_ACCEPT_EXTERNAL_TOKENS", [])

# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------
# Applies to every ViewSet that does not set its own throttle_classes. Rates are
# "<count>/<period>" with period s/sec, m/min, h/hour, d/day. Set the classes
# empty to turn throttling off entirely.
#
# The default cache is per process: with several workers the effective limit
# multiplies by the worker count. Configure a shared BaseThrottleCache via
# zeeb_api.throttling.set_throttle_cache() before deploying behind more than one.

_ANON_THROTTLE = "zeeb_api.throttling.AnonRateThrottle"
_USER_THROTTLE = "zeeb_api.throttling.UserRateThrottle"

DEFAULT_THROTTLE_CLASSES = env_list("DEFAULT_THROTTLE_CLASSES", [_ANON_THROTTLE, _USER_THROTTLE])
DEFAULT_THROTTLE_RATES = {{
    "anon": env_str("THROTTLE_ANON_RATE", "120/min"),
    "user": env_str("THROTTLE_USER_RATE", "1200/min"),
}}
# Trusted reverse proxies in front of the app; 0 means the client IP is used
# directly rather than read out of X-Forwarded-For.
THROTTLE_NUM_PROXIES = env_int("THROTTLE_NUM_PROXIES", 0) or None

# ---------------------------------------------------------------------------
# API versioning
# ---------------------------------------------------------------------------
# Clients send "X-API-Version: 1.0". A request without the header gets
# DEFAULT_VERSION; a version outside ALLOWED_VERSIONS is rejected with a 400
# API_VERSION_INVALID envelope. Set ALLOWED_VERSIONS empty to accept anything,
# or DEFAULT_VERSIONING_CLASS empty to switch versioning off.

_HEADER_VERSIONING = "zeeb_api.versioning.HeaderVersioning"

DEFAULT_VERSIONING_CLASS = env_str("DEFAULT_VERSIONING_CLASS", _HEADER_VERSIONING)
DEFAULT_VERSION = env_str("DEFAULT_VERSION", "1.0")
ALLOWED_VERSIONS = env_list("ALLOWED_VERSIONS", ["1.0"])
VERSION_PARAM = env_str("VERSION_PARAM", "version")
VERSION_HEADER = env_str("VERSION_HEADER", "X-API-Version")

# ---------------------------------------------------------------------------
# Logging — daily rotation into logs/
# ---------------------------------------------------------------------------
# create_app() applies this; do not call configure_logging() yourself, a second
# call resets the handlers this one installs.

LOGGING = {{
    "level": env_str("LOG_LEVEL", "DEBUG" if DEBUG else "INFO"),
    "json_logs": env_bool("JSON_LOGS", not DEBUG),
    "log_file": env_str("LOG_FILE", str(BASE_DIR / "logs" / "app.log")),
    "log_rotation": env_bool("LOG_ROTATION", True),
    "log_retention_days": env_int("LOG_RETENTION_DAYS", 30),
}}
'''

# The project urls.py is the same file the wiring layer repairs a project with,
# so there is exactly one definition of it.
URLS_PY = STANDARD_URLS_TEMPLATE

ASGI_PY = '''"""
{project_name} ASGI application.

Thin entry point. ``zeeb_api.create_app()`` builds everything from settings.py:
logging (LOGGING), middleware (MIDDLEWARE), the standard error envelope, JWT,
the routes from ROOT_URLCONF, the /health and /ready probes
(INSTALL_HEALTH_ROUTES), and a migration-aware startup lifespan. Configure
behavior in settings.py, not here.
"""

from zeeb_api import create_app

app = create_app("{project_name}.settings")
'''

ENV_TEMPLATE = '''# Local environment for {project_name}. Gitignored — never commit this file.
# See .env.example for every supported variable and its default.
# Real environment variables (container, CI) always override what is set here.

DEBUG=true

# Per-project signing key, generated by "zeeb startproject". Rotate it for
# production; rotating invalidates every access and refresh token in flight.
SECRET_KEY={secret_key}

# DATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/{project_name}
'''

ENV_EXAMPLE = r'''# Copy to .env and fill in. The values shown are the defaults from settings.py.
# Booleans: 1/true/yes/on vs 0/false/no/off. Lists: comma-separated.
# An empty value means "explicitly empty", not "use the default".

# --- Core ------------------------------------------------------------------
DEBUG=true
# Generate one with:  python -c "import secrets; print(secrets.token_urlsafe(64))"
SECRET_KEY=

# --- Database --------------------------------------------------------------
# DATABASE_URL=sqlite+aiosqlite:///db.sqlite3
# DATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/dbname
# DATABASE_URL=mysql+aiomysql://user:password@localhost:3306/dbname
# ENFORCE_MIGRATIONS=true

# --- API -------------------------------------------------------------------
# API_TITLE={project_name} API
# API_DESCRIPTION=
# API_VERSION=1.0.0
# API_PREFIX=/api/v1
# DEFAULT_LIMIT=20
# MAX_LIMIT=100

# --- CORS ------------------------------------------------------------------
# CORS_ALLOW_ORIGINS=http://localhost:3000,http://localhost:5173
#
# For a frontend on a preview URL that changes per build, match the host
# pattern instead of listing every deployment. Anchor it with $ and escape the
# dots — an unanchored pattern also matches attacker-controlled hostnames.
#   Lovable:  CORS_ALLOW_ORIGIN_REGEX=https://.*\.(lovable\.app|lovableproject\.com)$
#   Vercel:   CORS_ALLOW_ORIGIN_REGEX=https://.*\.vercel\.app$
#   Netlify:  CORS_ALLOW_ORIGIN_REGEX=https://.*\.netlify\.app$
# CORS_ALLOW_ORIGIN_REGEX=
# CORS_ALLOW_CREDENTIALS=true
# CORS_ALLOW_METHODS=*
# CORS_ALLOW_HEADERS=*
# CORS_EXPOSE_HEADERS=
# CORS_MAX_AGE=600

# --- Authentication --------------------------------------------------------
# JWT_SECRET_KEY=                    # defaults to SECRET_KEY
# JWT_ALGORITHM=HS256
# JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
# JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
# JWT_ISSUER=
# JWT_AUDIENCE=
# AUTH_URL_PREFIX=/auth
# AUTH_ENABLE_REGISTRATION=true
# AUTH_LOGIN_THROTTLE_RATE=10/min    # empty turns it off
# AUTH_LOAD_USER_FROM_DB=true

# --- OAuth2 / OIDC   (pip install "zeebpy[oauth]") -------------------------
# Setting a client id activates that provider and mounts its routes.
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# AZURE_CLIENT_ID=
# AZURE_CLIENT_SECRET=
# AZURE_TENANT_ID=common
# OAUTH_AUTO_CREATE_USERS=true
# OAUTH_LINK_BY_EMAIL=true
# OAUTH_REQUIRE_VERIFIED_EMAIL=true
# OAUTH_STATE_TTL_SECONDS=600
# OAUTH_REDIRECT_URI=
# OAUTH_SUCCESS_REDIRECT=
# OAUTH_ALLOWED_REDIRECT_HOSTS=
# OAUTH_ACCEPT_EXTERNAL_TOKENS=

# --- Rate limiting ---------------------------------------------------------
# THROTTLE_ANON_RATE=120/min
# THROTTLE_USER_RATE=1200/min
# THROTTLE_NUM_PROXIES=0
# DEFAULT_THROTTLE_CLASSES=zeeb_api.throttling.AnonRateThrottle,zeeb_api.throttling.UserRateThrottle

# --- API versioning --------------------------------------------------------
# DEFAULT_VERSIONING_CLASS=zeeb_api.versioning.HeaderVersioning
# DEFAULT_VERSION=1.0
# ALLOWED_VERSIONS=1.0               # empty accepts any version
# VERSION_HEADER=X-API-Version
# VERSION_PARAM=version

# --- Logging ---------------------------------------------------------------
# LOG_LEVEL=INFO
# JSON_LOGS=false
# LOG_FILE=logs/app.log
# LOG_ROTATION=true
# LOG_RETENTION_DAYS=30
'''

PROJECT_INIT_PY = '''"""
{project_name} - A Zeeb project.
"""

__version__ = "0.1.0"
'''

APPS_INIT_PY = '''"""
Apps package - your application modules go here.

Create a new app with: zeeb startapp <name>
"""
'''

REQUIREMENTS_TXT = '''# Zeeb ORM and API (zeeb_api ships inside the zeebpy distribution)
zeebpy[all] @ git+https://github.com/zeeb-cloud/zeebpy.git

# FastAPI
fastapi>=0.100.0
uvicorn[standard]>=0.23.0

# Development
pytest>=7.0.0
pytest-asyncio>=0.21.0
httpx>=0.24.0
'''

GITIGNORE = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.venv/
venv/
ENV/

# IDE
.idea/
.vscode/
*.swp
*.swo

# Testing
.pytest_cache/
.coverage
htmlcov/

# Database
*.sqlite3
*.db

# Environment — .env holds this project's signing key, .env.example does not
.env
.env.*
!.env.example

# Logs
logs/*.log

# Migrations
migrations/__pycache__/
'''

README_MD = '''# {project_name}

An async HTTP API built with zeebpy. Authentication, CORS, rate limiting, API
versioning, health probes, the standard error envelope and rotating logs are
already wired — everything is configured from `.env` (see `.env.example`).

Working on this with a coding agent? `AGENTS.md` is written for exactly that.

## What you already have

| | |
| --- | --- |
| `POST /api/v1/auth/register` | create an account |
| `POST /api/v1/auth/login` | exchange credentials for a token pair |
| `POST /api/v1/auth/refresh` | renew an expired access token |
| `GET /api/v1/auth/me` | the caller's identity |
| `GET /health`, `GET /ready` | liveness and readiness probes |
| `GET /docs`, `GET /openapi.json` | interactive docs and the schema |

Your own user model lives in `apps/accounts/models.py` — extend it there rather
than replacing it, since every foreign key already points at it.

## Run it

```bash
python -m venv .venv
source .venv/bin/activate            # .venv\\Scripts\\activate on Windows
pip install -r requirements.txt

python manage.py makemigrations      # create the initial migration
python manage.py migrate             # apply it
python manage.py createsuperuser     # optional: an admin account
python manage.py runserver           # http://127.0.0.1:9000
```

## Test it

```bash
pytest -q
```

The suite passes on a fresh clone, before any migration runs: the `db` fixture
builds the schema from the models. `tests/conftest.py` gives every test a `db`,
an anonymous `client`, an `auth_client` and an `admin_client` carrying real
tokens, plus `api_prefix`.

## Add a resource

```bash
python manage.py startapp blog --model Post
python manage.py makemigrations && python manage.py migrate
pytest -q
```

That writes the model, serializer, viewset, route registration and a passing
test, and registers the app. Without `--model` you get the same files carrying
the canonical example in their module docstring and nothing else.

## Commands

```bash
python manage.py showurls          # every route the project serves
python manage.py inspect --json    # apps, models, routes and settings, live
python manage.py frontend-brief    # an integration brief for a frontend
python manage.py check             # names the exact next command when it fails
python manage.py showmigrations
python manage.py migrate --rollback 1
python manage.py shell
```

Add `--json` to any of the reporting commands for one parseable object on
stdout instead of prose.

## Structure

```
{project_name}/
├── manage.py
├── AGENTS.md               conventions, for humans and coding agents
├── {project_name}/
│   ├── settings.py         all configuration, every value read from .env
│   ├── urls.py             the project router
│   └── asgi.py
├── apps/
│   └── accounts/           this project's user model
├── tests/                  conftest.py holds the shared fixtures
├── migrations/             flat — no versions/ subdirectory
├── logs/
├── .env                    secrets and configuration (gitignored)
├── .env.example
├── pyproject.toml
└── requirements.txt
```
'''
