"""Generated-test scaffolding: every built feature ships a runnable smoke suite.

``build_feature``/``apply_plan`` emit a ``generate_tests`` plan op (default
``tests=True``) that writes, per feature app, a pytest file exercising each
entity: an ORM roundtrip (create → get → update → delete), an anonymous API
list smoke for publicly readable endpoints, and a workflow-transition conflict
test (legal POST → 200, repeat → 409) where permissions allow. The shared
``tests/conftest.py`` boots the project app against an isolated sqlite file.

Generation is idempotent and **never overwrites an existing file** — the
generated tests are a starting point the user may edit freely.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from zeeb_agents._utils import AgentResult, agent_function
from zeeb_agents._utils.errors import fail
from zeeb_agents._utils.field_types import FIELD_TYPE_MAP

_PYTEST_INI = """\
[pytest]
asyncio_mode = auto
testpaths = tests
"""

_CONFTEST = '''\
"""Generated by zeeb build_feature. Safe to edit; regeneration never overwrites."""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Isolated test database — fresh file per test run, env wins over settings.
_TEST_DB = PROJECT_ROOT / "test_db.sqlite3"
_TEST_DB.unlink(missing_ok=True)
os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{_TEST_DB}"

SETTINGS_MODULE = "@SETTINGS_MODULE@"


@pytest.fixture(scope="session")
def app():
    from zeeb_api import create_app

    return create_app(SETTINGS_MODULE)


@pytest.fixture(scope="session")
def api_prefix(app):
    from zeeb_api.conf import get_settings

    return getattr(get_settings(), "API_PREFIX", "") or ""


@pytest.fixture()
async def db(app):
    """Connected database with all model tables created (schema from metadata)."""
    from zeeb_orm.db.connection import get_database, setup_database
    from zeeb_orm.models.base import _model_registry

    # Tables build lazily — materialize every registered model before create_all.
    for model in list(_model_registry.values()):
        model._get_table()
    database = get_database()
    if database is None:
        database = await setup_database(os.environ["DATABASE_URL"])
    await database.create_all()
    return database


@pytest.fixture()
async def client(app, db):
    from httpx import ASGITransport, AsyncClient

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as c:
        yield c
'''

_FILE_HEADER = '''\
"""Generated smoke tests for the '{app}' feature. Safe to edit."""

from __future__ import annotations
'''

# Sample literals per native field type (rendered with repr()).
_SAMPLE_VALUES = {
    "CharField": "sample",
    "TextField": "sample text",
    "IntegerField": 1,
    "SmallIntegerField": 1,
    "BigIntegerField": 1,
    "PositiveIntegerField": 1,
    "FloatField": 1.5,
    "DecimalField": "9.99",
    "BooleanField": True,
    "DateField": "2026-01-01",
    "DateTimeField": "2026-01-01T00:00:00",
    "TimeField": "12:00:00",
    "DurationField": 60,
    "JSONField": {},
    "UUIDField": "00000000-0000-0000-0000-000000000001",
    "EmailField": "sample@example.com",
    "SlugField": "sample",
    "URLField": "https://example.com",
    "GenericIPAddressField": "127.0.0.1",
}


def _native_type(field: dict) -> str:
    ftype = str(field.get("type", ""))
    return FIELD_TYPE_MAP.get(ftype) or FIELD_TYPE_MAP.get(ftype.lower()) or ftype


def _is_required_input(field: dict) -> bool:
    """Whether a create() call must supply this field."""
    if field.get("null") or field.get("blank") or "default" in field:
        return False
    if field.get("auto_now") or field.get("auto_now_add"):
        return False
    return _native_type(field) != "ManyToManyField"


def _sample_literal(field: dict) -> str | None:
    native = _native_type(field)
    if field.get("choices"):
        return repr(field["choices"][0][0])
    value = _SAMPLE_VALUES.get(native)
    if value is None:
        return None
    if native == "CharField" and isinstance(value, str):
        value = value[: int(field.get("max_length", 255))]
    return repr(value)


def _entity_create_kwargs(entity: dict) -> tuple[list[str], list[str], bool]:
    """(kwargs lines, required spec-internal fk targets, supported?) for create()."""
    kwargs: list[str] = []
    fk_targets: list[str] = []
    for field in entity.get("fields", []):
        if not _is_required_input(field):
            continue
        native = _native_type(field)
        if native in ("ForeignKey", "OneToOneField"):
            to = str(field.get("to", ""))
            if "." in to or to == "self":
                return [], [], False  # external/self target — ORM roundtrip skipped
            fk_targets.append(to)
            kwargs.append(f"{field['name']}_id={to.lower()}.id")
            continue
        literal = _sample_literal(field)
        if literal is None:
            return [], [], False  # no sample synthesis for this type
        kwargs.append(f"{field['name']}={literal}")
    return kwargs, fk_targets, True


def _render_orm_test(app: str, entity: dict, by_name: dict[str, dict]) -> str | None:
    name = entity["name"]
    kwargs, fk_targets, supported = _entity_create_kwargs(entity)
    lines: list[str] = []
    if not supported:
        return None
    setup: list[str] = []
    imports = {name}
    for target in fk_targets:
        target_entity = by_name.get(target)
        if target_entity is None:
            return None
        t_kwargs, t_fks, t_ok = _entity_create_kwargs(target_entity)
        if not t_ok or t_fks:  # one level of fk chasing is enough for a smoke test
            return None
        imports.add(target)
        setup.append(f"    {target.lower()} = await {target}.objects.create({', '.join(t_kwargs)})")
    lines.append(f"async def test_{name.lower()}_orm_roundtrip(db):")
    lines.append(f"    from apps.{app}.models import {', '.join(sorted(imports))}")
    lines.append("")
    lines.extend(setup)
    lines.append(f"    obj = await {name}.objects.create({', '.join(kwargs)})")
    lines.append(f"    fetched = await {name}.objects.get(id=obj.id)")
    lines.append("    assert fetched.id == obj.id")
    lines.append("    await obj.delete()")
    lines.append(f"    assert await {name}.objects.filter(id=obj.id).count() == 0")
    return "\n".join(lines)


def _render_api_smoke(entity: dict) -> str | None:
    if not entity.get("exposed") or not entity.get("prefix"):
        return None
    if entity.get("authentication") not in ("public", "read_only_public"):
        return None  # anonymous GET would 401 — no token-minting in generated tests
    name = entity["name"].lower()
    prefix = entity["prefix"]
    return (
        f"async def test_{name}_endpoint_lists(client, api_prefix):\n"
        f'    resp = await client.get(f"{{api_prefix}}/{prefix}/")\n'
        "    assert resp.status_code == 200"
    )


def _anonymous_transition_ok(entity: dict, transition: dict) -> bool:
    """Whether an unauthenticated POST may call this transition.

    A per-transition ``AllowAny`` overrides the endpoint permission; without
    one the transition inherits it, and only a ``public`` endpoint accepts an
    anonymous POST (``read_only_public`` opens GET only).
    """
    permission = transition.get("permission")
    if permission == "AllowAny":
        return True
    return permission is None and entity.get("authentication") == "public"


def _render_workflow_test(app: str, entity: dict) -> str | None:
    workflow = entity.get("workflow")
    if not workflow or not entity.get("exposed") or not entity.get("prefix"):
        return None
    transitions = workflow.get("transitions") or []
    # Pick a transition anonymous requests may call, leaving from the initial state.
    initial = workflow.get("initial")
    candidate = next(
        (
            t
            for t in transitions
            if _anonymous_transition_ok(entity, t) and initial in (t.get("from_states") or [])
        ),
        None,
    )
    if candidate is None:
        return None
    kwargs, fk_targets, supported = _entity_create_kwargs(entity)
    if not supported or fk_targets:
        return None
    name = entity["name"]
    field = workflow.get("field", "status")
    return "\n".join(
        [
            f"async def test_{name.lower()}_{candidate['name']}_transition_conflict(client, api_prefix, db):",
            f"    from apps.{app}.models import {name}",
            "",
            f"    obj = await {name}.objects.create({', '.join(kwargs)})",
            f'    first = await client.post(f"{{api_prefix}}/{entity["prefix"]}/{{obj.id}}/{candidate["name"]}/")',
            "    assert first.status_code == 200",
            f'    assert first.json()["{field}"] == "{candidate["to"]}"',
            f'    again = await client.post(f"{{api_prefix}}/{entity["prefix"]}/{{obj.id}}/{candidate["name"]}/")',
            "    assert again.status_code == 409",
        ]
    )


def _settings_module(project_root: Path) -> str | None:
    for item in sorted(project_root.iterdir()):
        if item.is_dir() and item.name != "apps" and (item / "settings.py").exists():
            return f"{item.name}.settings"
    return None


@agent_function
async def generate_tests(
    app: str,
    entities: list[dict],
    project_root: Path | None = None,
) -> AgentResult:
    """Write generated smoke tests for a feature app (idempotent, never overwrites).

    Creates ``tests/__init__.py``, ``tests/conftest.py`` (project app against
    an isolated sqlite file), a root ``pytest.ini`` (asyncio auto mode), and
    ``tests/test_<app>_generated.py`` with per-entity ORM roundtrips, anonymous
    API list smokes (publicly readable endpoints only), and workflow-transition
    conflict tests. Existing files are always left untouched.

    Args:
        app: The feature app the tests exercise.
        entities: Compiled entity descriptors — ``{"name", "prefix",
            "exposed", "authentication", "fields", "workflow"?}`` (the
            ``generate_tests`` plan op carries these; fields are compiled
            field specs).
        project_id: The host-assigned project id (required).

    Returns data (on success):
        created (list[str]): project-relative paths written.
        skipped (list[str]): paths that already existed and were kept.
        tests (int): number of test functions in the generated file (0 when
            the file already existed).
    """
    root = project_root
    if root is None or not Path(root).is_dir():
        return fail(f"Project not found: {root}", code="project_not_found")
    root = Path(root)
    settings_module = _settings_module(root)
    if settings_module is None:
        return fail(
            f"No settings.py found under {root}", code="project_not_found"
        )

    by_name = {e["name"]: e for e in entities}
    blocks: list[str] = []
    for entity in entities:
        for rendered in (
            _render_orm_test(app, entity, by_name),
            _render_api_smoke(entity),
            _render_workflow_test(app, entity),
        ):
            if rendered:
                blocks.append(rendered)

    created: list[str] = []
    skipped: list[str] = []

    def _write(relative: str, content: str) -> None:
        path = root / relative
        if path.exists():
            skipped.append(relative)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(relative)

    def _write_all() -> None:
        _write("pytest.ini", _PYTEST_INI)
        _write("tests/__init__.py", "")
        _write("tests/conftest.py", _CONFTEST.replace("@SETTINGS_MODULE@", settings_module))
        body = _FILE_HEADER.format(app=app)
        if blocks:
            body += "\n\n" + "\n\n\n".join(blocks) + "\n"
        _write(f"tests/test_{app}_generated.py", body)

    await asyncio.to_thread(_write_all)
    test_count = len(blocks) if f"tests/test_{app}_generated.py" in created else 0
    message = (
        f"Generated {len(created)} test file(s) for '{app}'"
        if created
        else f"Test files for '{app}' already exist; skipped"
    )
    return AgentResult(
        success=True,
        message=message,
        data={"created": created, "skipped": skipped, "tests": test_count},
    )
